language: node_js
dist: trusty
node_js:
  - 6
  - 8
script:
  - node --version
  - yarn --version
  - yarn install --cwd website
  - yarn run test:all
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules
    - website/node_modules